### PR TITLE
base: core20

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Review by Saviq — CHANGES_REQUESTED** [review]
As discussed, the `base: core20` change is too significant in my opinion to just flip it now. We should put a version with it in beta and have a call for testing.

**Comment by AlanGriffiths** [comment]
> put a version with it in beta

Done

**Comment by AlanGriffiths** [comment]
@Saviq I've merged the Ubuntu Core 20 related changes from master and updated the beta channel.

Ready to merge?

**Review by Saviq — APPROVED** [review]
OK then, let's get this in!

**Pull request merged**
