### PR TITLE
snap: use snapcraft's `package-repositories`

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
This should help with:

https://answers.launchpad.net/launchpad/+question/702182

**Comment by AlanGriffiths** [comment]
I don't see why it would help. If the PPA can't be found it doesn't matter how the add command is invoked

**Comment by Saviq** [comment]
> I don't see why it would help. If the PPA can't be found it doesn't matter how the add command is invoked

I'm told `add-apt-repository` is bad wrt error reporting. And the PPA obviously exists. There is a chance there's an infrastructure issue. I'll build this branch on LP to test.

Edit: https://launchpad.net/~saviq/+snap/test-mir-kiosk-ppas

**Comment by Saviq** [comment]
So yeah. It did help it looks like.

**Review by AlanGriffiths — COMMENTED** [review]
:shrug:

bors merge

**Review by AlanGriffiths — APPROVED** [review]

**Pull request merged**
